# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: check.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "NWitchGRPC.Protobuf.HealthCheckRequest" do
    optional :service, :string, 1
  end
  add_message "NWitchGRPC.Protobuf.HealthCheckResponse" do
    optional :status, :enum, 1, "NWitchGRPC.Protobuf.HealthCheckResponse.ServingStatus"
  end
  add_enum "NWitchGRPC.Protobuf.HealthCheckResponse.ServingStatus" do
    value :UNKNOWN, 0
    value :SERVING, 1
    value :NOT_SERVING, 2
  end
end

module NWitchGRPC
  module Protobuf
    HealthCheckRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("NWitchGRPC.Protobuf.HealthCheckRequest").msgclass
    HealthCheckResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("NWitchGRPC.Protobuf.HealthCheckResponse").msgclass
    HealthCheckResponse::ServingStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("NWitchGRPC.Protobuf.HealthCheckResponse.ServingStatus").enummodule
  end
end
