# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: push.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "NWitchGRPCClient.Push.PushRequest" do
    optional :nwitch_token, :string, 1
    optional :topic_name, :string, 2
    optional :title, :string, 3
    optional :message, :string, 4
  end
  add_message "NWitchGRPCClient.Push.PushResponse" do
    optional :success, :bool, 1
  end
end

module NWitchGRPCClient
  module Push
    PushRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("NWitchGRPCClient.Push.PushRequest").msgclass
    PushResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("NWitchGRPCClient.Push.PushResponse").msgclass
  end
end
